ROLE_SKILLS = {
    "Data Analyst": [
        {
            "name": "Python",
            "keywords": ["python"],
            "tier": "core",
            "suggestion": "Add Python projects to your resume — even simple data scripts count.",
        },
        {
            "name": "SQL",
            "keywords": ["sql", "mysql", "postgresql", "sqlite", "snowflake", "bigquery", "redshift"],
            "tier": "core",
            "suggestion": "Highlight SQL queries you've written — JOINs, aggregations, subqueries.",
        },
        {
            "name": "Excel",
            "keywords": ["excel", "spreadsheet", "vlookup", "pivot table", "google sheets", "vba"],
            "tier": "core",
            "suggestion": "Mention Excel skills like pivot tables, VLOOKUP, or data analysis add-ins.",
        },
        {
            "name": "Data Visualization",
            "keywords": ["data visualization", "matplotlib", "seaborn", "plotly", "bokeh", "altair", "data viz"],
            "tier": "core",
            "suggestion": "Describe dashboards or charts you've built to communicate insights.",
        },
        {
            "name": "Statistics",
            "keywords": ["statistics", "regression", "hypothesis testing", "confidence interval", "probability", "anova", "quantitative analysis"],
            "tier": "core",
            "suggestion": "Mention statistical methods you've used (regression, hypothesis testing, etc.).",
        },
        {
            "name": "Tableau",
            "keywords": ["tableau"],
            "implied_by": ["Power BI"],
            "tier": "important",
            "suggestion": "Create a Tableau Public portfolio with 2–3 dashboards and link it.",
        },
        {
            "name": "Power BI",
            "keywords": ["power bi"],
            "implied_by": ["Tableau"],
            "tier": "important",
            "suggestion": "Build a Power BI dashboard with sample data and mention it on your resume.",
        },
        {
            "name": "Pandas",
            "keywords": ["pandas", "dataframe"],
            "tier": "important",
            "suggestion": "Add a project showcasing data manipulation with Pandas (cleaning, groupby, merging).",
        },
        {
            "name": "NumPy",
            "keywords": ["numpy", "numerical computing"],
            "tier": "important",
            "suggestion": "Mention NumPy usage in numerical computations or data preprocessing.",
        },
        {
            "name": "Data Cleaning",
            "keywords": ["data cleaning", "data wrangling", "data preprocessing", "missing values", "outlier detection", "data quality", "feature engineering"],
            "tier": "important",
            "suggestion": "Describe a project where you cleaned messy real-world data.",
        },
        {
            "name": "ETL",
            "keywords": ["etl", "data pipeline", "data ingestion", "airflow", "dbt"],
            "tier": "nice",
            "suggestion": "Mention any ETL pipelines you've built or contributed to.",
        },
        {
            "name": "R",
            "keywords": ["r programming", "rstudio", "ggplot2", "tidyverse", "dplyr"],
            "tier": "nice",
            "suggestion": "If you know R, list specific packages you've used (ggplot2, dplyr, etc.).",
        },
        {
            "name": "Google Analytics",
            "keywords": ["google analytics", "ga4"],
            "tier": "nice",
            "suggestion": "Get Google Analytics certified (free) and add the certification.",
        },
        {
            "name": "A/B Testing",
            "keywords": ["a/b testing", "split testing", "experimentation", "controlled experiment"],
            "tier": "nice",
            "suggestion": "Describe an experiment or A/B test you designed and its outcome.",
        },
        {
            "name": "Reporting",
            "keywords": ["reporting", "data reporting", "business intelligence", "executive dashboard"],
            "tier": "nice",
            "suggestion": "Highlight reports or dashboards you've created for stakeholders.",
        },
    ],
    "Data Scientist": [
        {
            "name": "Python",
            "keywords": ["python"],
            "tier": "core",
            "suggestion": "List Python prominently with specific libraries you've used.",
        },
        {
            "name": "Machine Learning",
            "keywords": ["machine learning", "predictive model", "classification", "clustering", "random forest", "gradient boosting", "xgboost", "lightgbm", "svm", "supervised learning", "unsupervised learning"],
            "tier": "core",
            "suggestion": "Describe ML models you've built — mention the algorithm, dataset size, and results.",
        },
        {
            "name": "Statistics",
            "keywords": ["statistics", "probability", "regression", "bayesian"],
            "tier": "core",
            "suggestion": "Mention statistical methods and how you applied them to real problems.",
        },
        {
            "name": "SQL",
            "keywords": ["sql", "mysql", "postgresql"],
            "tier": "core",
            "suggestion": "Highlight SQL skills — data scientists query data constantly.",
        },
        {
            "name": "Scikit-learn",
            "keywords": ["scikit-learn", "sklearn"],
            "tier": "core",
            "suggestion": "Add a project using scikit-learn for classification, regression, or clustering.",
        },
        {
            "name": "Deep Learning",
            "keywords": ["deep learning", "neural network", "cnn", "rnn", "lstm", "transformer", "bert", "gpt", "autoencoder", "gan"],
            "tier": "important",
            "suggestion": "Build a deep learning project (image classification, text generation) and describe it.",
        },
        {
            "name": "Pandas",
            "keywords": ["pandas", "dataframe"],
            "tier": "important",
            "suggestion": "Showcase data wrangling with Pandas in a portfolio project.",
        },
        {
            "name": "TensorFlow",
            "keywords": ["tensorflow", "keras"],
            "tier": "important",
            "suggestion": "Add a TensorFlow/Keras project to demonstrate deep learning skills.",
        },
        {
            "name": "PyTorch",
            "keywords": ["pytorch"],
            "tier": "important",
            "suggestion": "Build a PyTorch-based model and describe the architecture choices you made.",
        },
        {
            "name": "Data Visualization",
            "keywords": ["data visualization", "matplotlib", "seaborn", "plotly", "data viz"],
            "tier": "important",
            "suggestion": "Show visualizations you've created — include tools like Matplotlib or Seaborn.",
        },
        {
            "name": "NLP",
            "keywords": ["natural language processing", "nlp", "text classification", "sentiment analysis", "named entity recognition", "word2vec", "spacy", "nltk", "hugging face", "language model"],
            "tier": "nice",
            "suggestion": "Try a text classification or sentiment analysis project to demonstrate NLP skills.",
        },
        {
            "name": "Computer Vision",
            "keywords": ["computer vision", "opencv", "image recognition", "object detection", "yolo", "image processing"],
            "tier": "nice",
            "suggestion": "Build an image classification or object detection project.",
        },
        {
            "name": "Feature Engineering",
            "keywords": ["feature engineering", "feature selection", "dimensionality reduction", "pca", "umap"],
            "tier": "nice",
            "suggestion": "Describe how you engineered features to improve model performance.",
        },
        {
            "name": "Big Data",
            "keywords": ["big data", "spark", "hadoop", "pyspark"],
            "tier": "nice",
            "suggestion": "Mention experience with Spark, Hadoop, or large-scale data processing.",
        },
        {
            "name": "Model Deployment",
            "keywords": ["model deployment", "mlops", "model serving", "flask api", "fastapi", "mlflow", "kubeflow", "sagemaker"],
            "tier": "nice",
            "suggestion": "Deploy a model via Flask/FastAPI and describe the end-to-end pipeline.",
        },
    ],
    "Software Engineer": [
        {
            "name": "Python",
            "keywords": ["python"],
            "tier": "core",
            "suggestion": "List Python with specific frameworks or use cases (scripting, backend, automation).",
        },
        {
            "name": "Data Structures",
            "keywords": ["data structures"],
            "tier": "core",
            "suggestion": "Mention DS&A proficiency — reference competitive programming or coursework.",
        },
        {
            "name": "Algorithms",
            "keywords": ["algorithms", "dynamic programming", "time complexity", "big-o", "sorting", "leetcode", "hackerrank", "competitive programming"],
            "tier": "core",
            "suggestion": "Highlight algorithm optimization work or competitive programming achievements.",
        },
        {
            "name": "Git",
            "keywords": ["git", "github", "gitlab", "version control"],
            "tier": "core",
            "suggestion": "Link your GitHub profile and ensure it has active repositories.",
        },
        {
            "name": "SQL",
            "keywords": ["sql", "mysql", "postgresql"],
            "tier": "core",
            "suggestion": "Add database experience — even simple CRUD projects demonstrate SQL skills.",
        },
        {
            "name": "Java",
            "keywords": ["java"],
            "tier": "important",
            "suggestion": "Add Java projects if you have experience — it's widely used in enterprise.",
        },
        {
            "name": "JavaScript",
            "keywords": ["javascript", "node.js", "typescript", "es6"],
            "tier": "important",
            "suggestion": "Build a small full-stack project with Node.js or React to show JS skills.",
        },
        {
            "name": "C++",
            "keywords": ["c++", "cpp"],
            "tier": "important",
            "suggestion": "Mention C++ in system-level or performance-critical projects.",
        },
        {
            "name": "REST APIs",
            "keywords": ["rest api", "restful api", "web api", "graphql", "grpc", "swagger", "openapi", "webhook"],
            "tier": "important",
            "suggestion": "Describe APIs you've designed or consumed — mention endpoints and auth methods.",
        },
        {
            "name": "System Design",
            "keywords": ["system design", "software architecture", "scalable system", "load balancing", "design patterns", "cap theorem"],
            "tier": "important",
            "suggestion": "Add high-level design experience — even describing design decisions in projects helps.",
        },
        {
            "name": "Docker",
            "keywords": ["docker", "containerization"],
            "tier": "nice",
            "suggestion": "Dockerize one of your projects and mention it — shows deployment awareness.",
        },
        {
            "name": "CI/CD",
            "keywords": ["ci/cd", "continuous integration", "github actions", "jenkins"],
            "tier": "nice",
            "suggestion": "Set up GitHub Actions for a project and mention automated testing/deployment.",
        },
        {
            "name": "AWS",
            "keywords": ["aws", "amazon web services", "ec2", "s3", "lambda"],
            "tier": "nice",
            "suggestion": "Deploy a project on AWS Free Tier and describe the services used.",
        },
        {
            "name": "Linux",
            "keywords": ["linux", "unix", "bash", "shell script"],
            "tier": "nice",
            "suggestion": "Mention Linux command-line proficiency or shell scripting experience.",
        },
        {
            "name": "Agile",
            "keywords": ["agile", "scrum", "sprint", "kanban"],
            "tier": "nice",
            "suggestion": "Mention Agile/Scrum experience from team projects or internships.",
        },
    ],
    "Frontend Developer": [
        {
            "name": "HTML",
            "keywords": ["html", "html5"],
            "tier": "core",
            "suggestion": "Mention semantic HTML5 usage in your web projects.",
        },
        {
            "name": "CSS",
            "keywords": ["css", "css3", "sass", "scss", "tailwind"],
            "tier": "core",
            "suggestion": "Showcase responsive layouts you've built — mention CSS frameworks used.",
        },
        {
            "name": "JavaScript",
            "keywords": ["javascript", "es6", "dom manipulation", "async javascript", "promises"],
            "tier": "core",
            "suggestion": "Highlight JavaScript projects — DOM manipulation, async/await, fetch calls.",
        },
        {
            "name": "React",
            "keywords": ["react", "react hooks", "usestate", "useeffect", "jsx", "redux", "next.js"],
            "tier": "core",
            "suggestion": "Build a React app with hooks, state management, and API integration.",
        },
        {
            "name": "Responsive Design",
            "keywords": ["responsive design", "media queries", "mobile-first"],
            "tier": "core",
            "suggestion": "Describe how your projects adapt to mobile/tablet/desktop viewports.",
        },
        {
            "name": "TypeScript",
            "keywords": ["typescript"],
            "tier": "important",
            "suggestion": "Convert a JavaScript project to TypeScript to demonstrate type safety skills.",
        },
        {
            "name": "Vue.js",
            "keywords": ["vue.js", "vue"],
            "tier": "important",
            "suggestion": "Build a small Vue.js app to show framework versatility.",
        },
        {
            "name": "Angular",
            "keywords": ["angular"],
            "tier": "important",
            "suggestion": "Add an Angular project — it's popular in enterprise frontend teams.",
        },
        {
            "name": "Git",
            "keywords": ["git", "github"],
            "tier": "important",
            "suggestion": "Link your GitHub with well-organized frontend repositories.",
        },
        {
            "name": "Testing",
            "keywords": ["jest", "cypress", "unit testing", "e2e testing", "testing framework"],
            "tier": "important",
            "suggestion": "Write unit tests (Jest) or E2E tests (Cypress) for a frontend project.",
        },
        {
            "name": "Webpack",
            "keywords": ["webpack", "vite", "rollup", "bundler"],
            "tier": "nice",
            "suggestion": "Mention build tool experience — custom Webpack/Vite configs show depth.",
        },
        {
            "name": "Figma",
            "keywords": ["figma"],
            "tier": "nice",
            "suggestion": "Collaborate with designers in Figma and mention design-to-code experience.",
        },
        {
            "name": "Accessibility",
            "keywords": ["accessibility", "a11y", "wcag", "aria"],
            "tier": "nice",
            "suggestion": "Audit a project for WCAG compliance and describe the improvements you made.",
        },
        {
            "name": "Performance",
            "keywords": ["performance optimization", "lighthouse", "core web vitals", "lazy loading"],
            "tier": "nice",
            "suggestion": "Run Lighthouse on your projects and mention specific optimizations.",
        },
        {
            "name": "REST APIs",
            "keywords": ["rest api", "fetch api", "axios", "api integration", "graphql"],
            "tier": "nice",
            "suggestion": "Show that you can integrate with APIs — mention specific endpoints you've consumed.",
        },
    ],
    "Backend Developer": [
        {
            "name": "Python",
            "keywords": ["python", "django", "flask", "fastapi"],
            "tier": "core",
            "suggestion": "List Python backend frameworks you've used (Django, Flask, FastAPI).",
        },
        {
            "name": "SQL",
            "keywords": ["sql", "mysql", "postgresql", "sqlite"],
            "tier": "core",
            "suggestion": "Highlight complex queries, schema design, or database optimization work.",
        },
        {
            "name": "REST APIs",
            "keywords": ["rest api", "restful api", "web api", "api design"],
            "tier": "core",
            "suggestion": "Describe APIs you've built — mention routes, auth, and documentation.",
        },
        {
            "name": "Git",
            "keywords": ["git", "github", "gitlab"],
            "tier": "core",
            "suggestion": "Link your GitHub and ensure repos have clear READMEs and commit history.",
        },
        {
            "name": "Linux",
            "keywords": ["linux", "unix", "bash", "shell script"],
            "tier": "core",
            "suggestion": "Mention server administration, shell scripting, or Linux deployment experience.",
        },
        {
            "name": "Java",
            "keywords": ["java", "spring", "spring boot"],
            "tier": "important",
            "suggestion": "Add Java/Spring Boot projects if applicable — common in enterprise backend.",
        },
        {
            "name": "Node.js",
            "keywords": ["node.js", "express"],
            "tier": "important",
            "suggestion": "Build a REST API with Express.js to show Node.js proficiency.",
        },
        {
            "name": "Docker",
            "keywords": ["docker", "containerization", "dockerfile"],
            "tier": "important",
            "suggestion": "Dockerize your backend projects and mention multi-stage builds.",
        },
        {
            "name": "NoSQL",
            "keywords": ["nosql", "mongodb", "redis", "cassandra", "dynamodb"],
            "tier": "important",
            "suggestion": "Add a project using MongoDB or Redis to show NoSQL experience.",
        },
        {
            "name": "AWS",
            "keywords": ["aws", "amazon web services", "azure", "gcp", "cloud computing"],
            "tier": "important",
            "suggestion": "Deploy on AWS/Azure/GCP Free Tier and describe the architecture.",
        },
        {
            "name": "Kubernetes",
            "keywords": ["kubernetes", "k8s"],
            "tier": "nice",
            "suggestion": "Learn K8s basics and mention container orchestration experience.",
        },
        {
            "name": "CI/CD",
            "keywords": ["ci/cd", "continuous integration", "github actions", "jenkins"],
            "tier": "nice",
            "suggestion": "Set up a CI/CD pipeline (GitHub Actions, Jenkins) for automated deployment.",
        },
        {
            "name": "Microservices",
            "keywords": ["microservices"],
            "tier": "nice",
            "suggestion": "Describe a project with microservice architecture — mention communication patterns.",
        },
        {
            "name": "Message Queues",
            "keywords": ["kafka", "rabbitmq", "message queue", "event-driven"],
            "tier": "nice",
            "suggestion": "Add async processing experience — even a simple producer/consumer demo helps.",
        },
        {
            "name": "Caching",
            "keywords": ["memcached", "caching", "cache invalidation", "in-memory cache"],
            "tier": "nice",
            "suggestion": "Mention caching strategies (Redis, Memcached, CDN) you've implemented for performance.",
        },
    ],
}

ROLE_DESCRIPTIONS = {
    "Data Analyst": "Analyze data to help organizations make informed decisions.",
    "Data Scientist": "Build predictive models and extract insights from complex data.",
    "Software Engineer": "Design, develop, and maintain software systems.",
    "Frontend Developer": "Build user-facing web interfaces and experiences.",
    "Backend Developer": "Design and maintain server-side application logic and infrastructure.",
}

WEIGHT_MULTIPLIERS = {
    "core": 3,
    "important": 2,
    "nice": 1,
}
